
[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["luxon", "axios"]

# SPA fallback: send all unmatched routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
