[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  autoLaunch = false

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["luxon", "axios"]
