[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["netlify/functions/**/*"]

[dev]
  autoLaunch = false

[[scheduled.functions]]
  name = "cron-purge-banner"
  schedule = "0 13 * * 6" # 8am CST Saturday (13:00 UTC during CST); note DST caveat.
