[functions]
  node_bundler = "esbuild"

# Weekly auto-start (optional)
# [[scheduled.functions]]
#   name = "start-week"
#   cron = "0 9 * * 1" # every Monday at 09:00 server time

# Voting window: schedule twice to handle DST in Central Time (America/Chicago)
[[scheduled.functions]]
  name = "open-vote"
  cron = "0 20 * * 5" # Fridays 20:00 UTC (3pm during Daylight time)

[[scheduled.functions]]
  name = "open-vote"
  cron = "0 21 * * 5" # Fridays 21:00 UTC (3pm during Standard time)

[[scheduled.functions]]
  name = "close-vote"
  cron = "0 23 * * 5" # Fridays 23:00 UTC (6pm during Daylight time)

[[scheduled.functions]]
  name = "close-vote"
  cron = "0 0 * * 6" # Saturdays 00:00 UTC (6pm during Standard time)

[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "strict-origin-when-cross-origin"
